version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  commands:
    - git submodule update --init --recursive
    - pip install -e .
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html
