version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  commands:
    - python - m pip install --upgrade pip setuptools wheel
    - git submodule update --init --recursive
    - python - m pip install -e .
    - python - m pip install -r docs/requirements.txt
    - python - m sphinx-build -b html docs $READTHEDOCS_OUTPUT/html
