#!/usr/bin/env python3
#

import os
import re

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_copybutton",
    "sphinxcontrib.rsvgconverter",
    "sphinxcontrib.moderncmakedomain",
    "sphinx.ext.intersphinx",
]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = [".templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = {'.rst': 'restructuredtext'}

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "py3dm"
copyright = "2025, StudioWEngineers"
author = "StudioWEngineers"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# Read the listed version
VERSION_REGEX = re.compile(
    r"^\s*#\s*define\s+PY3DM_VERSION_([A-Z]+)\s+(.*)$", re.MULTILINE)

repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
version_file = os.path.join(repo_root, "src", "bindings", "bindings.h")

with open(version_file) as f:
    matches = dict(VERSION_REGEX.findall(f.read()))
    version = "{MAJOR}.{MINOR}.{PATCH}".format(**matches)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [".build", "release.rst"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
default_role = "any"

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = 'monokai'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<version> documentation".
html_title = f"{project} v{version} documentation"

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#  html_static_path = ["_static"]

#  html_css_files = [ ]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = "py3dm_doc"

# -- Options for LaTeX output ---------------------------------------------

latex_engine = "pdflatex"

latex_maketitle = r'''
\begin{titlepage}
	\begingroup
	\drop = 0.3\textheight
	\hbox{
		\hspace*{0.01\textwidth}
		\rule{3pt}{\dimexpr\textheight-28pt\relax}
		\hspace*{0.1\textwidth}
		\parbox[b]{1.0\textwidth}{
			\vbox{
				{\noindent\HUGE\bfseries py3dm }\\[1.0\baselineskip]
				{\noindent\huge\bfseries Python bindings for OpenNURBS}\\[3\baselineskip]
				{\LARGE  How to use}\\[3\baselineskip]
				\vspace{\drop}

				\begin{tabular}{l l}
				{Author:}&{StudioWEngineers}\\
				{Reviser:}&{-}\\
				{Corresponding author:}&{studio.w.engineers@gmail.com}\\
				{}&{}\\
				{First issue:}&{July, 2025}\\
				{Last editing:}&{\today}\\
				{px3dm version:}&{v0.2.0}\\
				\end{tabular}
				\vspace{0.05\textheight}
			}% end of vbox
		}% end of parbox
	}% end of hbox

	\endgroup

\end{titlepage}
'''
#\rule{3pt}{\dimexpr\textheight-28pt\relax}


latex_maketitle = r'''
\begin{titlepage}
  \vspace*{2cm}
  {\Huge\bfseries py3dm \par}
  \vspace{1cm}
  {\LARGE\bfseries Python bindings for OpenNURBS\par}
  \vspace{2cm}
  {\Large How to use\par}
  \vspace{3cm}
  \begin{tabular}{rl}
    Author: & StudioWEngineers \\
    Reviser: & - \\
    Corresponding author: & studio.w.engineers@gmail.com \\
    First issue: & July 2025 \\
    Last editing: & \today \\
    px3dm version: & v0.2.0 \\
  \end{tabular}
  \vfill
\end{titlepage}
'''
latex_maketitle = r'''
\begin{titlepage}
  \begingroup
  \hbox{
    \rule{3pt}{0.9\textheight}%
    \hspace{1cm}
    \parbox[b]{0.8\textwidth}{
      \raggedright
      {\Huge\bfseries py3dm}\\[1.0\baselineskip]
      {\huge\bfseries Python bindings for OpenNURBS}\\[3\baselineskip]
      {\LARGE How to use}\\[3\baselineskip]
      \begin{tabular}{ll}
        Author: & StudioWEngineers \\
        Reviser: & - \\
        Corresponding author: & studio.w.engineers@gmail.com \\
        First issue: & July, 2025 \\
        Last editing: & \today \\
        py3dm version: & v0.2.0 \\
      \end{tabular}
    }
  }
  \endgroup
\end{titlepage}
'''

latex_maketitle = r'''
\begin{titlepage}
\pagenumbering{gobble}
  \begingroup
  \vfill
  \hbox{
    \rule{3pt}{0.9\textheight}%
    \hspace{1cm}
    \parbox[t]{0.8\textwidth}{
      \raggedright
      {\Huge\bfseries py3dm}\\[1.0\baselineskip]
      {\LARGE\bfseries Python bindings for OpenNURBS}\\[3\baselineskip]
      {\LARGE How to use}\\[3\baselineskip]
      \begin{tabular}{ll}
        Author: & StudioWEngineers \\
        Reviser: & - \\
        Corresponding author: & studio.w.engineers@gmail.com \\
        First issue: & July, 2025 \\
        Last editing: & \today \\
        py3dm version: & v0.2.0 \\
      \end{tabular}
    }
  }
  \vfill
  \endgroup
\end{titlepage}
'''

latex_maketitle1 = r'''
\begin{titlepage}
  \begingroup
  \vspace*{.1cm}
  \hbox{%
    % Vertical line: 3pt wide, 90% text height
    \rule{3pt}{0.9\textheight}%
    \hspace{1cm}%
    % Text block, left-aligned, 0.8 width
    \parbox[b]{0.8\textwidth}{%
      \raggedright
      {\Huge\bfseries py3dm}\\[1.0\baselineskip]
      {\LARGE\bfseries Python bindings for OpenNURBS}\\[3\baselineskip]
      {\LARGE How to use}\\[3\baselineskip]
      \begin{tabular}{ll}
        Author: & StudioWEngineers \\
        Reviser: & - \\
        Corresponding author: & studio.w.engineers@gmail.com \\
        First issue: & July, 2025 \\
        Last editing: & \today \\
        py3dm version: & v0.2.0 \\
      \end{tabular}
    }%
  }
  \vfill
  \endgroup
\end{titlepage}
'''

latex_maketitle2 = r'''
\begin{titlepage}
  \begingroup
  \vspace*{3cm}  % space from top - adjust to your liking

  % Use a tabular to place vertical line and text side-by-side neatly
  \noindent
  \begin{tabular}{@{}l p{0.8\textwidth}@{}}
    \rule{3pt}{0.8\textheight} & % vertical line, left column
    {%
      \raggedright
      {\Huge\bfseries py3dm}\\[1.5em]
      {\LARGE\bfseries Python bindings for OpenNURBS}\\[3em]
      {\LARGE How to use}\\[3em]
      \begin{tabular}{ll}
        Author: & StudioWEngineers \\
        Reviser: & - \\
        Corresponding author: & studio.w.engineers@gmail.com \\
        First issue: & July, 2025 \\
        Last editing: & \today \\
        py3dm version: & v0.2.0 \\
      \end{tabular}
    }
  \end{tabular}

  \endgroup
\end{titlepage}
'''

latex_maketitle = r'''
\begin{titlepage}
\pagenumbering{gobble}
  \begingroup
  \vspace*{1cm}  % adjust space from top here
  \noindent
  \begin{tabular}{@{}l p{0.8\textwidth}@{}}
    \rule{3pt}{0.9\textheight} &  % vertical line left column
    {%
      \raggedright
      {\Huge\bfseries py3dm}\\[1.0\baselineskip]
      {\LARGE\bfseries Python bindings for OpenNURBS}\\[3\baselineskip]
      {\LARGE How to use}\\[3\baselineskip]
      \begin{tabular}{ll}
        Author: & StudioWEngineers \\
        Reviser: & - \\
        Corresponding author: & studio.w.engineers@gmail.com \\
        First issue: & July, 2025 \\
        Last editing: & \today \\
        py3dm version: & v0.2.0 \\
      \end{tabular}
    }
  \end{tabular}
  \vfill
  \endgroup
\end{titlepage}
'''

latex_maketitle = r'''
\begin{titlepage}
\noindent
\pagenumbering{gobble}
  \begingroup
  \vspace*{2cm} % adjust top space here
  \noindent
  \begin{minipage}[t]{0.025\linewidth}
    \rule{3pt}{\dimexpr\ht\strutbox + 6cm\relax} % vertical line height
  \end{minipage}%
  \hspace{1cm}%
  \begin{minipage}[t]{0.8\linewidth}
    \vspace{0pt} % force top alignment inside minipage
    \raggedright
    {\Huge\bfseries py3dm}\\[1.0\baselineskip]
    {\LARGE\bfseries Python bindings for OpenNURBS}\\[3\baselineskip]
    {\LARGE How to use}\\[3\baselineskip]
    \begin{tabular}{ll}
      Author: & StudioWEngineers \\
      Reviser: & - \\
      Corresponding author: & studio.w.engineers@gmail.com \\
      First issue: & July, 2025 \\
      Last editing: & \today \\
      py3dm version: & v0.2.0 \\
    \end{tabular}
  \end{minipage}
  \vfill
  \endgroup
\end{titlepage}
'''

latex_maketitle = r'''
\begin{titlepage}
\pagenumbering{gobble}
  \begingroup
  \vspace*{2cm} % space from top
  \noindent
  \begin{tabular}{@{}p{0.03\textwidth}@{\hspace{1cm}}p{0.8\textwidth}@{}}
    \rule{3pt}{6cm} &
    {%
      \raggedright
      {\Huge\bfseries py3dm}\\[1.0\baselineskip]
      {\LARGE\bfseries Python bindings for OpenNURBS}\\[3\baselineskip]
      {\LARGE How to use}\\[3\baselineskip]
      \begin{tabular}{ll}
        Author: & StudioWEngineers \\
        Reviser: & - \\
        Corresponding author: & studio.w.engineers@gmail.com \\
        First issue: & July, 2025 \\
        Last editing: & \today \\
        py3dm version: & v0.2.0 \\
      \end{tabular}
    }
  \end{tabular}
  \vfill
  \endgroup
\end{titlepage}
'''

latex_maketitle = r'''
\begin{titlepage}
\pagenumbering{gobble}
  \begingroup
  \vspace*{2cm} % space from top of page

  \noindent
  \vbox to 0pt{%
    \hbox to \textwidth{%
      \rule{3pt}{6cm}%
      \hspace{1cm}%
      \begin{minipage}[t]{0.8\textwidth}
        \raggedright
        {\Huge\bfseries py3dm}\\[1.0\baselineskip]
        {\LARGE\bfseries Python bindings for OpenNURBS}\\[3\baselineskip]
        {\LARGE How to use}\\[3\baselineskip]
        \begin{tabular}{ll}
          Author: & StudioWEngineers \\
          Reviser: & - \\
          Corresponding author: & studio.w.engineers@gmail.com \\
          First issue: & July, 2025 \\
          Last editing: & \today \\
          py3dm version: & v0.2.0 \\
        \end{tabular}
      \end{minipage}%
      \hfill
    }
  }

  \vfill
  \endgroup
\end{titlepage}
'''

latex_maketitle = r'''
\begin{titlepage}
\thispagestyle{empty} % override Sphinx’s default
\pagenumbering{gobble}
\begingroup
\vspace*{2cm}  % Adjust top margin
\noindent
\begin{minipage}[t]{\textwidth}
  \begin{minipage}[t]{0.03\textwidth}
    \rule{3pt}{15cm} % vertical bar height
  \end{minipage}
  \hspace{1cm}
  \begin{minipage}[t]{0.85\textwidth}
    \raggedright
    {\Huge\bfseries py3dm}\\[1.0\baselineskip]
    {\LARGE\bfseries Python bindings for OpenNURBS}\\[2\baselineskip]
    {\LARGE How to use}\\[2\baselineskip]
    \begin{tabular}{ll}
      Author: & StudioWEngineers \\
      Reviser: & - \\
      Corresponding author: & studio.w.engineers@gmail.com \\
      First issue: & July, 2025 \\
      Last editing: & \today \\
      py3dm version: & v0.2.0 \\
    \end{tabular}
  \end{minipage}
\end{minipage}
\vfill
\endgroup
\end{titlepage}
'''

latex_maketitle4 = r'''
\begin{titlepage}
\thispagestyle{empty} % override Sphinx’s default
\vspace*{2cm}
\noindent
\hbox to \textwidth{%
  \vtop{\rule{3pt}{15cm}}%
  \hspace{1cm}%
  \vtop{\hsize=0.8\textwidth
        \raggedright
        ... your text ...
  }%
}
\end{titlepage}
'''

latex_maketitle = r'''
\begin{titlepage}
\thispagestyle{empty}
\pagenumbering{gobble}
\begingroup
\vspace*{2cm}
\noindent
\begin{minipage}[t]{\textwidth}
  \begin{minipage}[t]{0.03\textwidth}
    \rule{3pt}{\dimexpr\ht\strutbox+10cm\relax} % height based on text block
  \end{minipage}
  \hspace{1cm}
  \begin{minipage}[t]{0.85\textwidth}
    \raggedright
    {\Huge\bfseries py3dm}\\[1.0\baselineskip]
    {\LARGE\bfseries Python bindings for OpenNURBS}\\[2\baselineskip]
    {\LARGE How to use}\\[2\baselineskip]
    \begin{tabular}{ll}
      Author: & StudioWEngineers \\
      Reviser: & - \\
      Corresponding author: & studio.w.engineers@gmail.com \\
      First issue: & July, 2025 \\
      Last editing: & \today \\
      py3dm version: & v0.2.0 \\
    \end{tabular}
  \end{minipage}
\end{minipage}
\vfill
\endgroup
\end{titlepage}
'''

latex_maketitle = r'''
\begin{titlepage}
\thispagestyle{empty}
\pagenumbering{gobble}
\begingroup
\vspace*{2cm}
\setlength{\arrayrulewidth}{3pt} % thicker vertical line
\noindent
\begin{tabular}{@{}p{0.03\textwidth}|@{\hspace{1cm}} p{0.85\textwidth}@{}}
  % Left narrow column — empty, vertical line will appear between columns &
  &
  % Right column with all text content
  \raggedright
  \vspace*{1cm}
  {\Huge\bfseries py3dm}\\[3.0\baselineskip]
  {\LARGE\bfseries Python bindings for OpenNURBS}\\[7\baselineskip]
  {\LARGE How to use}\\[20\baselineskip]
  \begin{tabular}{ll}
    Author: & StudioWEngineers \\
    Reviser: & - \\
    Corresponding author: & studio.w.engineers@gmail.com \\
    First issue: & July, 2025 \\
    Last editing: & \today \\
    py3dm version: & v0.2.0 \\
    \vspace*{1cm}
  \end{tabular}
\end{tabular}
\vfill
\endgroup
\end{titlepage}
'''

latex_elements = {

    'papersize': 'a4paper',
    'pointsize': '10pt',
    'classoptions': ',openany,oneside',
#    'sphinxsetup': 'verbatimwithframe=false, margin=1.25in',


'preamble': r"""
% === Use full TeX Gyre Cursor font family ===
\usepackage{tgcursor}   % TeX Gyre Cursor monospace font
\renewcommand*\rmdefault{qcr} % set serif default to tgcursor (mono)
\renewcommand*\sfdefault{qcr} % set sans default to tgcursor (mono)
\renewcommand*\ttdefault{qcr} % monospace
\renewcommand*\familydefault{\ttdefault} % monospace everywhere

% === Fix section heading fonts ===
\usepackage{titlesec}
\titleformat{\section}
  {\Large\ttfamily}
  {\thesection}{1em}{}
\titleformat{\subsection}
  {\large\ttfamily}
  {\thesubsection}{1em}{}

% === Localization ===
\usepackage[nodayofweek,level]{datetime}
\addto\captionsenglish{%
  \renewcommand{\contentsname}{Table of Contents}
}
""",

   'maketitle': latex_maketitle
}
latex_docclass = {'howto': 'book'}
latex_documents = [
    ('index', 'py3dm.tex', 'py3dm Documentation', 'StudioWEngineers', 'manual'),
]
nitpicky = True
latex_use_latex_multicolumn = True

#primary_domain = "python"
highlight_language = "python"

extensions = ['autoapi.extension']
autoapi_dirs = ['../build/cp312-abi3-win_amd64/Release']