#!/usr/bin/env python3
#

import os
import re

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_copybutton",
    "sphinxcontrib.rsvgconverter",
    "sphinxcontrib.moderncmakedomain",
    "sphinx.ext.intersphinx",
]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = [".templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "py3dm"
copyright = "2025, StudioWEngineers"
author = "StudioWEngineers"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# Read the listed version
VERSION_REGEX = re.compile(
    r"^\s*#\s*define\s+PY3DM_VERSION_([A-Z]+)\s+(.*)$", re.MULTILINE)

repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
version_file = os.path.join(repo_root, "src", "bindings", "bindings.h")

with open(version_file) as f:
    matches = dict(VERSION_REGEX.findall(f.read()))
    version = "{MAJOR}.{MINOR}.{PATCH}".format(**matches)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [".build", "release.rst"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
default_role = "any"

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = 'monokai'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<version> documentation".
html_title = f"{project} v{version} documentation"

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#  html_static_path = ["_static"]

#  html_css_files = [ ]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = "py3dm_doc"

# -- Options for LaTeX output ---------------------------------------------

latex_engine = "pdflatex"

latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '10pt',
    'classoptions': ',openany,oneside',

    'sphinxsetup': 'verbatimwithframe=false, margin=1.25in',

    'preamble': r"""
% === Unicode and Symbol Support ===
\usepackage{MnSymbol}
\DeclareUnicodeCharacter{25CB}{\ensuremath{\circ}}
\DeclareUnicodeCharacter{25CF}{\ensuremath{\bullet}}
\DeclareUnicodeCharacter{21B5}{\ensuremath{\rhookswarrow}}
\DeclareUnicodeCharacter{2194}{\ensuremath{\leftrightarrow}}

% === Language and Typography ===
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage[final]{microtype}
\usepackage[hidelinks]{hyperref}
\usepackage{multirow}
\usepackage{lmodern}
\usepackage{everysel}
\usepackage{graphicx}
\usepackage[nodayofweek,level]{datetime}
\usepackage{lipsum,kantlipsum}

\renewcommand*\familydefault{\ttdefault}
\EverySelectfont{%
  \fontdimen2\font=0.4em%
  \fontdimen3\font=0.2em%
  \fontdimen4\font=0.1em%
  \fontdimen7\font=0.1em%
  \hyphenchar\font=`\-%
}

\addto\captionsenglish{%
  \renewcommand{\contentsname}{Table of Contents}
}

% === Title Page Metadata Macros ===
\makeatletter
\def\StudioWAuthor#1{\gdef\@StudioWAuthor{#1}}
\def\@StudioWAuthor{\@latex@warning@no@line{No \noexpand\StudioWAuthor given}}
\def\StudioWReviser#1{\gdef\@StudioWReviser{#1}}
\def\@StudioWReviser{\@latex@warning@no@line{No \noexpand\StudioWReviser given}}
\def\StudioWTitle#1{\gdef\@StudioWTitle{#1}}
\def\@StudioWTitle{\@latex@warning@no@line{No \noexpand\StudioWTitle given}}
\def\StudioWSubTitle#1{\gdef\@StudioWSubTitle{#1}}
\def\@StudioWSubTitle{\@latex@warning@no@line{No \noexpand\StudioWSubTitle given}}
\def\StudioWFirstIssue#1{\gdef\@StudioWFirstIssue{#1}}
\def\@StudioWFirstIssue{\@latex@warning@no@line{No \noexpand\StudioWFirstIssue given}}
\def\StudioWCurrentIssue#1{\gdef\@StudioWCurrentIssue{#1}}
\def\@StudioWCurrentIssue{\@latex@warning@no@line{No \noexpand\StudioWCurrentIssue given}}
\def\StudioWRevision#1{\gdef\@StudioWRevision{#1}}
\def\@StudioWRevision{\@latex@warning@no@line{No \noexpand\StudioWRevision given}}
\def\StudioWDocumentID#1{\gdef\@StudioWDocumentID{#1}}
\def\@StudioWDocumentID{\@latex@warning@no@line{No \noexpand\StudioWDocumentID given}}
\def\StudioWEmail#1{\gdef\@StudioWEmail{#1}}
\def\@StudioWEmail{\@latex@warning@no@line{No \noexpand\StudioWEmail given}}
\makeatother

% === Title Page Layout ===
\makeatletter
\newcommand*{\MakeFirstPage}{
  \thispagestyle{empty}
  \begingroup
  \drop = 0.3\textheight
  \vspace*{\baselineskip}
  \vfill
  \hbox{
    \hspace*{0.01\textwidth}
    \rule{3pt}{\dimexpr\textheight-28pt\relax}
    \hspace*{0.1\textwidth}
    \parbox[b]{1.0\textwidth}{
      \vbox{
        {\noindent\HUGE\bfseries \@StudioWTitle}\\[1.0\baselineskip]
        {\noindent\huge\bfseries \@StudioWSubTitle}\\[3\baselineskip]
        {\LARGE  Internal Note}\\[3\baselineskip]
        \vspace{\drop}
        \begin{tabular}{l l}
        {Author:}&{\@StudioWAuthor}\\
        {Reviser:}&{\@StudioWReviser}\\
        {Corresponding author:}&{\@StudioWEmail}\\
        {}&{}\\
        {First issue:}&{\@StudioWFirstIssue}\\
        {Last editing:}&{\@StudioWCurrentIssue}\\
        {Revision:}&{\@StudioWRevision}\\
        {Document ID:}&{\@StudioWDocumentID}
        \end{tabular}
        \vspace{0.05\textheight}
        {\noindent \small{This document consists of \thelastsheet \ pages, cover included.}}
        \vspace{0.085\textheight}
      }
    }
  }
  \endgroup
}
\makeatother

\newcommand*\NewPage{\newpage\null\thispagestyle{empty}\newpage}
\raggedbottom
""",

    'maketitle': r'''
\MakeFirstPage
\clearpage
''',
}

# LaTeX document configuration: source file, output filename, title, author, doc class
latex_documents = [
    (master_doc, "py3dm.tex", "py3dm Documentation", author, "manual"),
]

# Optional: add this later in conf.py to inject metadata into the title page
latex_elements['preamble'] += rf"""
\StudioWTitle{{{project}}}
\StudioWSubTitle{{{version}}}
\StudioWAuthor{{{author}}}
\StudioWReviser{{}}
\StudioWEmail{{your.email@example.com}}
\StudioWFirstIssue{{2025-01-01}}
\StudioWCurrentIssue{{2025-08-02}}
\StudioWRevision{{1.0}}
\StudioWDocumentID{{DOC-001}}
"""

# Optional logo at top of title page
# latex_logo = 'xxx.png'

primary_domain = "python"
highlight_language = "python"
