name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Just one build Python since ABI3 targets 3.12+

      - name: Install build tools on macOS
        if: runner.os == 'macOS'
        run: |
          brew install ninja cmake

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.23

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --output-dir dist .
        env:
          CIBW_BUILD: "cp312-* cp313-* cp314-*"
          CIBW_SKIP: "*-musllinux* *-win32 cp3*t-*"
          CIBW_TEST_SKIP: "*"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ENVIRONMENT: >
            CMAKE_GENERATOR=Ninja
            CMAKE_BUILD_TYPE=Release
          CIBW_BUILD_VERBOSITY: 3

      - name: Upload wheels to GitHub (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: py3dm-wheels
          path: dist/*.whl

  publish:
    name: Upload to PyPI
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          name: py3dm-wheels
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
