name: Tests - PyPy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_relevant_changes:
    name: check for relevant changes
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
      - name: check changed files
        uses: tj-actions/changed-files@v45.0.4
        id: changed-files
        with:
          files: |
            .github/workflows/workflow_ci_pypy.yml
            py3dm/__init__.py
            src/**
            tests/**
            CMakeLists.txt
            pyproject.toml
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  pypy-build:
    name: PyPy ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: [check_relevant_changes]
    if: needs.check_relevant_changes.outputs.any_changed == 'true'

    strategy:
      matrix:
        python-version: [pypy3.9, pypy3.10]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: update submodules
        run: git submodule update --init --recursive

      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Display Python version
        run: |
          python --version
          python -c "import sys; print(sys.implementation)"

      - name: Manually install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build-core>=0.11.5 nanobind build

      - name: Install libuuid (dev headers and linker support)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y uuid-dev

      - name: Build wheel without build isolation
        run: |
          python -m build --wheel --no-isolation

      - name: Install built wheel
        run: |
          pip install --no-deps --ignore-requires-python dist/*.whl

      - name: test ${{ matrix.python-version }}
        run: |
          cd tests
          python -m unittest discover --verbose
        shell: bash
